/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here
 } //_CODE_:button1:12356:

 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider:238566:
  if (ardu==null) return;
  // max is 20 ms
  ardu.setSpeed (20-source.getValueI());
} //_CODE_:slider:238566:

public void loadFile(GButton source, GEvent event) { //_CODE_:b1:775415:
  if (ardu==null) return;
  selectInput("Select a file to process:", "fileSelected");
} //_CODE_:b1:775415:

public void selectPort(GButton source, GEvent event) { //_CODE_:b2:349409:
  selectPort();
} //_CODE_:b2:349409:

public void stopMachine(GButton source, GEvent event) { //_CODE_:b4:790048:
  if (mm==null) return;
  mm.stopMotions();
} //_CODE_:b4:790048:

public void startMachine(GButton source, GEvent event) { //_CODE_:b3:494559:
  if (mm==null) return;
  mm.startMotions();
} //_CODE_:b3:494559:

public void detachMotor(GButton source, GEvent event) { //_CODE_:b5:534519:
  if (ardu==null) return;
  ardu.detachMotor();
} //_CODE_:b5:534519:

public void attachMotor(GButton source, GEvent event) { //_CODE_:b6:939197:
  if (ardu==null) return;
  ardu.attachMotor();
} //_CODE_:b6:939197:

public void servoDown(GButton source, GEvent event) { //_CODE_:b8:483598:
  if (ardu==null) return;
  ardu.servoDown ();
} //_CODE_:b8:483598:

public void servoUp(GButton source, GEvent event) { //_CODE_:b7:241942:
  if (ardu==null) return;
  ardu.servoUp ();
} //_CODE_:b7:241942:

public void stepLeft(GButton source, GEvent event) { //_CODE_:b9:873758:
  if (ardu==null) return;
  ardu.stepOnceLeft();
} //_CODE_:b9:873758:

public void stepRight(GButton source, GEvent event) { //_CODE_:b10:606575:
  if (ardu==null) return;
  ardu.stepOnceRight();
} //_CODE_:b10:606575:



// Create all the GUI controls.
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  slider = new GSlider(this, 384, 240, 100, 40, 10.0);
  slider.setLimits(1.0, 1.0, 20.0);
  slider.setNbrTicks(20);
  slider.setNumberFormat(G4P.DECIMAL, 0);
  slider.setOpaque(false);
  slider.addEventHandler(this, "slider1_change1");
  b1 = new GButton(this, 48, 120, 80, 30);
  b1.setText("Load file");
  b1.addEventHandler(this, "loadFile");
  title = new GLabel(this, 149, 10, 192, 20);
  title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  title.setText("Spider Web Machine");
  title.setTextBold();
  title.setOpaque(true);
  label1 = new GLabel(this, 48, 72, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Setup");
  label1.setOpaque(true);
  b2 = new GButton(this, 48, 180, 80, 28);
  b2.setText("Select port");
  b2.addEventHandler(this, "selectPort");
  label2 = new GLabel(this, 323, 253, 60, 12);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Speed");
  label2.setOpaque(false);
  b4 = new GButton(this, 216, 180, 80, 30);
  b4.setText("Stop");
  b4.setLocalColorScheme(GCScheme.RED_SCHEME);
  b4.addEventHandler(this, "stopMachine");
  b3 = new GButton(this, 216, 120, 80, 30);
  b3.setText("Start");
  b3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  b3.addEventHandler(this, "startMachine");
  label3 = new GLabel(this, 264, 72, 176, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Controls");
  label3.setOpaque(true);
  b5 = new GButton(this, 312, 120, 80, 30);
  b5.setText("Detach motor");
  b5.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  b5.addEventHandler(this, "detachMotor");
  b6 = new GButton(this, 312, 180, 80, 30);
  b6.setText("AttachMotor");
  b6.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  b6.addEventHandler(this, "attachMotor");
  b8 = new GButton(this, 408, 180, 80, 30);
  b8.setText("Servo DOWN");
  b8.addEventHandler(this, "servoDown");
  b7 = new GButton(this, 408, 120, 80, 30);
  b7.setText("Servo UP");
  b7.addEventHandler(this, "servoUp");
  b9 = new GButton(this, 216, 240, 32, 32);
  b9.setText("Left");
  b9.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  b9.addEventHandler(this, "stepLeft");
  b10 = new GButton(this, 264, 240, 32, 32);
  b10.setText("Right");
  b10.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  b10.addEventHandler(this, "stepRight");
}

// Variable declarations
// autogenerated do not edit
GSlider slider;
GButton b1;
GLabel title;
GLabel label1;
GButton b2;
GLabel label2;
GButton b4;
GButton b3;
GLabel label3;
GButton b5;
GButton b6;
GButton b8;
GButton b7;
GButton b9;
GButton b10;